spring:
  application:
    name: AI_Project

  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PW}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false

  api:
    hospital:
      endpoint: ${End_Point}
      encoding-key: ${Encoding_Key}
      decoding-key: ${Decoding_Key}

